[package]
name = "ezlatexdoc"
version = "0.1.0"
authors = ["Rebecca Turner <rbt@sent.as>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
indoc = "0.3.4"
quick-error = "1.2.2"

[dev-dependencies]
pretty_assertions = "0.6.1"

[lib]
name = "ezlatexdoc"
path = "src/lib.rs"

[[bin]]
name = "ezlatexdoc"
path = "src/main.rs"
